import type { Metadata } from "next";
import "@/styles/globals.css";
import { Sofia_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sofiaSans = Sofia_Sans({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-sofia",
  display: "swap", // Usando o display swap para garantir renderização mais rápida
  fallback: ["sans-serif"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${sofiaSans.className}`}>{children}</body>
    </html>
  );
}
